version: '3.8'

services:
  webserver-livetracking:
    container_name: webserver-livetracking
    build: ./
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db-livetracking
  
  db-livetracking:
    container_name: db-master-livetracking
    image: postgres:14.7-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=livetracking

  cache-livetracking:
    image: redis:7.2.3-alpine
    restart: always
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"

  pgadmin:
    container_name: pgadmin4-livetracking
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@foodverse.in
      PGADMIN_DEFAULT_PASSWORD: root123
    ports:
      - "5051:80"

volumes:
  pgdata:
  